[package]
name = "ogg"
version = "0.3.1"
authors = ["est31 <MTest31@outlook.com>"]
description = "Ogg container decoder and encoder written in pure Rust"
license = "BSD-3-Clause"
keywords = ["ogg", "decoder", "encoder", "xiph"]
documentation = "https://docs.rs/ogg/0.3.1"
repository = "https://github.com/est31/ogg"
readme = "README.md"

[lib]
name = "ogg"

[dependencies]
byteorder = "0.5"

